jobs: 
  mail_on_push:
    runs_on: ubuntu-latest
    steps:
      - name: Send mail
      uses: dawidd6/action-send-mail@v3

with:
  server_address: smtp.gmail.com
  server_port: 465
  username: ${{secrets.MAIL_USERNAME}}
  password: ${{secrets.MAIL_PASSWORD}}

subject: something
  body: nothing
  to: daniel.dogadajev@gmail.com
  from: github

on: [push]
